package main

// http://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice?name=3d&issueCount=30

import (
	"fmt"
	"log"

	"github.com/gogf/gf/net/ghttp"
)

func main() {
	client := ghttp.NewClient()
	client.SetHeader("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36")
	// client.SetTimeOut(time.Second * 10)

	url := "http://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice?name=3d&issueCount=30"
	response, err := client.Get(url)
	if err != nil {
		fmt.Println("error")
		return
	}
	defer response.Body.Close()
	log.Println(response.ReadAllString())
	// var auto PlsAutoGenerated
	// jsoniter.NewDecoder(response.Body).Decode(&auto)
	// println(len(auto.Value.List))
}
