project_name: quote

env:
    - AppVersion=`git tag --sort=-version:refname | head -n 1`"
    
before:
  hooks:
    - go mod tidy

builds:
  - binary: quote

    main: ./
    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w -X main.AppVersion={{.Env.AppVersion}}

    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64

changelog:
  skip: true

archives:
  - id: quote
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
